# Use root/example as user/password credentials
version: '2.4'

services:

  db:
    image: mariadb
    #volumes:
    #    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 20002:8080